name: Documentation

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'src/**'

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.15.0"
          cache: 'pnpm'

      - run: cd docu && pnpm install && pnpm exec playwright install
      - run: cd docu/scripts/images && pnpm i && pnpm exec playwright install
      - run: cd docu && pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docu/src/.vitepress/dist
          cname: docu.xn--rseau-constellation-bzb.ca